# Generated by Django 3.1.5 on 2021-01-06 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='amount',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='price',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='markets.device', verbose_name='device'),
        ),
    ]
