# Generated by Django 3.1.5 on 2021-01-07 19:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_auto_20210106_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Price', 'verbose_name_plural': 'Prices'},
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='markets.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='device',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='markets.company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 7), verbose_name='Date'),
        ),
    ]
