# Generated by Django 3.1.5 on 2021-01-12 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_auto_20210108_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='markets.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='price',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='markets.company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(help_text='Price in tenge', verbose_name='Price'),
        ),
    ]
